name: Docker build and deploy workflow
on:
  schedule:
  - cron: "*/1 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: docker build and deploy
      run: curl --location --request POST ${{ secrets.DOCKER_HUB_API }}
      shell: bash
